<?php

/**
 * @file
 * Module file for unig.
 */

use Drupal\Core\Routing\RouteMatchInterface;

function unig_page_attachments(array &$attachments) {
    $attachments['#attached']['library'][] = 'unig/unig';
}



/**
 * @defgroup unig
 * @ingroup ost
 * @{
 * Universal Gallery
 * Each Item (Image, File) is an Node
 * Organized in Projects also as Nodes
 * and Albums(Image) / Groups(Files) as Taxonomy
 *
 *
 */

/**
 * Implements hook_help().
 *
 *
 * @see https://www.drupal.org/documentation/help-text-standards
 *
 * @see hook_help()
 */
function unig_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'unig.upload':
      // Help text for the simple page registered for this path.
      return t('');

    case 'help.page.unig':
      // Help text for the admin section, using the module name in the path.
        return t('');
  }
}

/**
 * @} End of "defgroup unig".
 */
